LOCAL_PATH := $(call my-dir)

#GMsgs
include $(CLEAR_VARS)
LOCAL_MODULE := GMsgs
LOCAL_MODULES_TAGS := optional
LOCAL_SRC_FILES := apps/Msgs.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Messaging
LOCAL_MODULE_PREFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

#GDialer
include $(CLEAR_VARS)
LOCAL_MODULE := GDialer
LOCAL_MODULES_TAGS := optional
LOCAL_SRC_FILES := apps/Dialer.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Dialer
LOCAL_MODULE_PREFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

#GContacts
include $(CLEAR_VARS)
LOCAL_MODULE := GContacts
LOCAL_MODULES_TAGS := optional
LOCAL_SRC_FILES := apps/Contacts.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Contacts
LOCAL_MODULE_PREFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

#GCalc
include $(CLEAR_VARS)
LOCAL_MODULE := GCalc
LOCAL_MODULES_TAGS := optional
LOCAL_SRC_FILES := apps/Calc.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Calculator
LOCAL_MODULE_PREFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
